# Vale configuration file

# Set the global minimum alert level
MinAlertLevel = warning

# Define the paths for your styles (custom rules)
StylesPath = .vale/styles

Vocab = asic

# Enable built-in Vale styles
[*.{md,txt,tex}]
# You can enable the built-in rules from Vale's core
# BasedOnStyles = Vale, Microsoft, Google
BasedOnStyles = Vale

# Exclude some files or directories
[*.{log,aux,yml}]