name: CV build
# run-name: ${{ github.actor }} is learning GitHub Actions
on: [push, workflow_dispatch]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - uses: actions/checkout@v4
      # - name: Setup Fonts
      #   run: |
      #     apt update
      #     apt install -y fonts-roboto-unhinted
      - name: Font check
        run: fc-match Roboto
      - name: Building CV with bibliography
        run: |
          make cv.pdf   # First LaTeX pass
          make bib      # Run Biber to process bibliography
          make cv.pdf   # Second LaTex pass for references
          make cv.pdf   # Third LaTeX pass to finalize cross-references
      - name: Store CV
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: |
            my_cv/obj/cv.pdf
      - name: Building Cover Letter
        run: |
          make coverletter.pdf
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            my_cv/obj/cv.pdf
            my_cv/obj/coverletter.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
