name: CV build
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: thomasweise/texlive
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - uses: actions/checkout@v3
      - name: Setup Fonts
        run: make font_setup
      - name: Building CV
        run: make cv.pdf
      - name: Store CV
        uses: actions/upload-artifact@v3
        with:
            name: cv
            path: |
            my_cv/cv.pdf
