name: Lint Files

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Run yamllint
        run: yamllint .

      - name: Install editorconfig-checker
        run: |
          mkdir -p tools && cd tools
          wget https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.2.0/ec-linux-amd64.tar.gz
          tar -xzf ec-linux-amd64.tar.gz
          ./bin/ec-linux-amd64 ./my_cv/

      - name: Run EditorConfig Checker
        run: ./tools/bin/ec-linux-amd64 ./my_cv/

