name: Grammar checks

on: [push, pull_request]

jobs:
  vale:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install vale
        run: |
          make vale_setup

      - name: Generate text files
        run: |
          make my_cv/obj/cv.txt
          make my_cv/obj/coverletter.txt

      - name: Vale check
        run: |
          make vale_run